# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

flutter_application_path = '../flutter_embedding_addon'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterEmbedding' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  install_all_flutter_pods(flutter_application_path)

  target 'FlutterEmbeddingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterEmbeddingUITests' do
    # Pods for testing
  end

end
